routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegisterController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'BlogController@home');
Route::get('/about', 'BlogController@about');
Route::get('/blog', 'BlogController@index');
Route::resource('blog', BlogController::class);

Route::get('/login', [LoginController::class, 'index'])->name('login')->middleware('guest');
Route::post('/login', [LoginController::class, 'authenticate'])->name('auth');
Route::post('/logout', [LoginController::class, 'logout'])->name('logout');
Route::get('/register', [RegisterController::class, 'index'])->name('register')->middleware('guest');
Route::post('/register', [RegisterController::class, 'store'])->name('store');

Route::get('/welcome', function(){
    return view('welcome');
});

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;


class Blog extends Model
{
    use HasFactory, Sluggable;

     /**
     * fillable
     *
     * @var array
     */
    protected $fillable = [
        'image', 'title', 'slug', 'content'
    ];

    public function getRouteKeyName()
        {
            return 'slug';
        }

    public function sluggable(): array
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    public function category(){
        return $this->belongsTo('Category');
    }

}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Blog;
use App\Models\User;
use App\Models\Order;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use \Cviebrock\EloquentSluggable\Services\SlugService;

class BlogController extends Controller
{
     /**
     * index
     *
     * @return void
     */

     public function index(Blog $blog, Request $request){
         //$orders = Order::search('search')->latest()->get();
         $blogs = Blog::latest()->paginate(10);
         return view('blog.index',["title" => "Dashboard", "title1" => "Dashboard"], compact('blog', 'blogs'));
     }

    /**
      * home
      *
      * @return void
      */

     public function home(Blog $blog){
         $blogs = Blog::latest()->paginate(10);
         return view('blog.home',["title" => "Home", "title1" => "dadangKonelo"], compact('blog', 'blogs'));
     }

     /**
      * about
      *
      * @return void
      */

      public function about(){
         return view('blog.about', ["title" => "About", "title1" => "About"]);
      }

     /**
      * show
      *
      * @param int $id
      * @return void
      */

     public function show(Blog $blog){
        return view('blog.show', ['blog' => $blog, "title" => "Show", "title1" => "dadangKonelo"], compact('blog'));
     }

     /**
     *create
     *
     * @return void
     */

     public function create(){
         return view('blog.create');
     }

     /**
      *store
      *
      * @param mixed $request
      * @return void
      */

      public function store(Request $request){
          $this->validate($request, [
            'image'     => 'required|image|mimes:png,jpg,jpeg',
            'title'     => 'required',
            'content'   => 'required',
          ]);

          $image = $request->file('image');
          $image->storeAs('public/blogs', $image->hashName());

          $slug = SlugService::createSlug(Blog::class, 'slug', $request->title);

          $blog = Blog::create([
              'image' => $image->hashname(),
              'title' => $request->title,
              'slug' => $slug,
              'content' => $request->content
          ]);

          if ($blog) {
              return redirect()->route('blog.index')->with(['success' => 'Data berhasil disimpan!']);
          }
          else {
              return redirect()->route('blog.index')->with(['error' => 'Data gagal disimpan!']);
          }
      }

      /**
      * edit
      *
      * @param mixed $blog
      * @return void
      */

      public function edit(Blog $blog){

          return view('blog.edit', compact('blog'));
      }

      /**
      * update
      *
      * @param mixed $request
      * @param mixed $blog
      * @return void
      */

      public function update(Request $request, Blog $blog){

        $this->validate($request, [
              'title' => 'required',
              'content' => 'required',
          ]);

          $blog = Blog::findOrFail($blog->id);

          if ($request->file('image') == "") {

            $blog->update([
                'title' => $request->title,
                'slug' => $slug,
                'content' => $request->content,
            ]);

            $blog->save();
        }

            else {

                Storage::disk('local')->delete('public/blog/'.$blog->image);

                $image = $request->file('image');
                $image->storeAs('public/blogs', $image->hashName());

                $slug = SlugService::createSlug(Blog::class, 'slug', $request->title);


                $blog->update([
                  'image' => $image->hashname(),
                  'title' => $request->title,
                  'slug' => $slug,
                  'content' => $request->content,
                ]);

                $blog->save();

            }

            if ($blog) {
                return redirect()->route('blog.index')->with(['success' => 'Data berhasil diupdate!']);
            }
            else {
                return redirect()->route('blog.index')->with(['error' => 'Data gagal diupdate!']);
            }
      }

      /**
      * destroy
      *
      * @param mixed $slug
      * @return void
      */

      public function destroy(Blog $blog){

        Blog::destroy($blog->id);

        if ($blog) {
            return redirect()->route('blog.index')->with(['success' => 'Data berhasil dihapus']);
        }
        else {
            return redirect()->route('blog.index')->with(['error' => 'Data gagal dihapus']);
        }

      }




}

resources/views/blog/about.blade.php
@extends('blog.main')

@section('container')

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card bourder-0 rounded">
                <div class="card-body">
                    <img class="team-member-img img-fluid rounded-circle p-4" src="img\denji.jpg" alt="Siapa hayo???" width="300">
                    <h5 style="margin: 40px">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Blanditiis voluptates exercitationem dolor dignissimos illo repudiandae suscipit delectus, similique, ab rem vel tenetur eveniet ratione assumenda. Commodi eaque laboriosam dolorum accusamus quis praesentium facere error fugiat ad cupiditate, distinctio itaque sequi, deleniti sit vero corporis dolorem voluptas incidunt doloribus necessitatibus unde perspiciatis amet culpa. Dignissimos corporis itaque nobis animi doloribus vero molestiae sint iusto accusamus ea, exercitationem aliquam obcaecati quia necessitatibus asperiores veritatis perferendis qui maxime corrupti consequuntur voluptate quo! Maiores.</h5>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/blog/create.blade.php
@auth
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add Post - dadangKonelo</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body style="background: lightgray">

    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body">
                        <form action="{{ route('blog.store') }}" method="POST" enctype="multipart/form-data">

                            @csrf

                            <div class="form-group">
                                <label class="font-weight-bold">IMAGE</label>
                                <input type="file" class="form-control @error('image') is-invalid @enderror" name="image">

                                <!-- error message untuk title -->
                                @error('image')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                                <div class="form-group">
                                <label class="font-weight-bold">TITLE</label>
                                <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title') }}" placeholder="Add your title here">

                                <!-- error message untuk title -->
                                @error('title')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">CONTENT</label>
                                <textarea class="form-control @error('content') is-invalid @enderror" name="content" rows="5">{{ old('content') }}</textarea>

                                <!-- error message untuk content -->
                                @error('content')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <button type="submit" class="btn btn-md btn-primary">SAVE</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace( 'content' );
</script>
</body>
</html>
@endauth

resources/views/blog/edit.blade.php
@auth
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Edit Post - dadangKonelo</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body style="background: lightgray">

    <div class="container mt-5 mb-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body">
                        <form action="/blog/{{ $blog->slug }}/edit" method="POST" enctype="multipart/form-data">
                            @csrf
                            @method('PUT')

                            <div class="form-group">
                                <label class="font-weight-bold">IMAGE</label>
                                <input type="file" class="form-control" name="image">
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">TITLE</label>
                                <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ old('title', $blog->title) }}" placeholder="Edit your title here">

                                <!-- error message untuk title -->
                                @error('title')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label class="font-weight-bold">CONTENT</label>
                                <textarea class="form-control @error('content') is-invalid @enderror" name="content" rows="5">{{ old('content', $blog->content) }}</textarea>

                                <!-- error message untuk content -->
                                @error('content')
                                    <div class="alert alert-danger mt-2">
                                        {{ $message }}
                                    </div>
                                @enderror
                            </div>

                            <button type="submit" class="btn btn-md btn-primary">UPDATE</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace( 'content' );
</script>
</body>
</html>
@endauth

resources/views/blog/home.blade.php
@extends('blog.main')

@section('container')
<tbody>

@if($blogs->count())

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card mb-3 py-3">
                <div class="text-center bg-auto" style="padding: 30px">
                    <img src="{{ Storage::url('public/blogs/').$blogs[0]->image }}" class="card-img-top" style="width: 60%;" alt="{{ $blogs[0]->title }}">
                </div>
                <div class="card-body text-center">
                        <h3 class="card-title"><a href="{{ route('blog.show', $blogs[0]->slug) }}" class="text-decoration-none text-dark">{{ $blogs[0]->title }}</a></h3>
                        <p class="card-text">{!! Str::of($blogs[0]->content)->words(30) !!}</p>
                        <p class="card-text"><small class="text-muted">{{ $blogs[0]->created_at->diffForHumans() }}</small></p>
                        <a href="{{ route('blog.show', $blogs[0]->slug) }}" class="btn btn-sm btn-primary ms-auto">Read more</a>
                    </div>
                </div>
            </div>
        </div>
</div>

@else

    <p class="text-center fs-3">No Post found</p>

@endif


<div class="container">
    <div class="row">
        @foreach ($blogs->skip(1) as $blog)
        <div class="col-md-4 mb-3">
                <div class="card text-center">
                    <img src="{{ Storage::url('public/blogs/').$blog->image }}" class="card-img-top" alt="{{ $blog->title }}">
                    <div class="card-body">
                        <h5 class="card-title"><a href="{{ route('blog.show', $blog->slug) }}" class="text-decoration-none text-dark">{{ $blog->title }}</a></h5>
                        <p class="card-text">{!! Str::of($blog->content)->words(20) !!}</p>
                        <p class="card-text"><small class="text-muted">{{ $blog->created_at->diffForHumans() }}</small></p>
                        <a href="{{ route('blog.show', $blog->slug) }}" class="btn btn-sm btn-primary ms-auto">Read more</a>
                    </div>
                </div>
            </div>
            @endforeach
        </div>
    </div>
</tbody>

{{ $blogs->links() }}

@endsection

resources/views/blog/index.blade.php
@extends('blog.main')

@section('container')
@auth
        <div class="container mt5">
            <div class="row">
                <div class="col-md-12">
                    <div class="card bourder-0 shadow rounded">
                        <div class="card-body">
                            <a href="/blog/create" class="btn btn-md btn-success mb-3" title="Nambah ora? masa ora nambah">Add</a>
                            <table class="table table-bordered" style="text-align: center; overflow-y: auto">
                                <thread>
                                    <tr>
                                        <th scope="col">Image</th>
                                        <th scope="col">Title</th>
                                        <th scope="col">Content</th>
                                        <th scope="col">Action</th>
                                    </tr>
                                </thread>
                                <tbody>
                                    @forelse ($blogs as $blog)
                                    <tr>
                                    <td class="text-center">
                                        <img src="{{ Storage::url('public/blogs/').$blog->image }}" class="rounded" style="width: 150px">
                                    </td>
                                    <td>{{ Str::of($blog->title)->title() }}</td>
                                    <td>{!! Str::of($blog->content)->words(30) !!}</td>
                                    <td>
                                        <a href="{{ route('blog.show', $blog->slug) }}" class="badge bg-info"><span data-feather="eye"></span></a>
                                        <form onsubmit="return confirm('Apakah Anda Yakin ?');" action="/blog/{{ $blog->slug }}" method="POST">
                                            <a href="/blog/{{ $blog->slug }}/edit" class="badge bg-warning"><span data-feather="edit"></span></a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="badge bg-danger border-0"><span data-feather="x-circle"></span></button>
                                        </form>
                                    </td>
                                </tr>
                              @empty
                                  <div class="alert alert-danger">
                                      Post hasn't added.
                                  </div>
                              @endforelse
                            </tbody>
                          </table>
                          {{ $blogs->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>

@endauth
@endsection

resources/views/blog/main.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <!-- <link rel="stylesheet" href="/css/style.css"> -->
    <link rel="shortcut icon" href="https://www.pngitem.com/pimgs/m/11-116289_dk-projects-dk-logo-hd-png-download.png" type="image/x-icon">
    <title>dadangKonelo | {{ $title }} </title>
</head>
<body>

<nav class="navbar navbar-light bg-light fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><h2>{{ $title1 }}</h2></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        @auth
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Welcome, {{ auth()->user()->name }}</h5>
        @else
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Menu</h5>
        @endauth
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link {{ ($title === 'Home') ? 'active' : '' }}" aria-current="page" href="/">Home</a>
          </li>
          @auth
          <li class="nav-item">
            <a class="nav-link {{ ($title === 'Dashboard') ? 'active' : '' }}" href="/blog">Dashboard</a>
          </li>
          @endauth
          <li class="nav-item">
            <a class="nav-link {{ ($title === 'About') ? 'active' : '' }}" href="/about">About</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="offcanvasNavbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Account
            </a>
            <ul class="dropdown-menu" aria-labelledby="offcanvasNavbarDropdown">
                @auth
                <li>
                    <form action="{{ route('logout') }}" method="post">
                        @csrf
                        <button type="submit" class="dropdown-item"><i class="bi bi-box-arrow-right"></i>Logout</button>
                    </form>
                </li>
                @else
                <li><a class="dropdown-item" href="/login"><i class="bi bi-box-arrow-in-right"></i> Login</a></li>
                <li><a class="dropdown-item" href="/register"><i class="bi bi-pencil-square"></i> Register</a></li>
              @endauth
            </ul>
          </li>
        </ul>
        <form class="d-flex" action="/blog">
          <input class="form-control me-2" type="text" placeholder="Search" name="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </div>
</nav>

    <div class="row mt-5">
        <div class="row mt-5">
            <@yield('container')
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://unpkg.com/feather-icons"></script>
    <script>
        feather.replace()
        //message with toastr
        @if(session()->has('success'))

            toastr.options =
                    {
                        "closeButton" : true,
                        "progressBar" : true
                    }

            toastr.success('{{ session('success') }}');

        @elseif(session()->has('error'))

            toastr.options =
                    {
                        "closeButton" : true,
                        "progressBar" : true
                    }

            toastr.error('{{ session('error') }}');

        @endif
    </script>
</body>
</html>

resources/views/blog/show.blade.php
@extends('blog.main')

@section('container')



<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="card bourder-0 rounded">
                <div class="card-body">
                    <h2 style="margin: 30px; text-align: center;">{{ $blog->title }}</h2>
                    <div class="text-center py-5">
                        <img src="{{ Storage::url('public/blogs/').$blog->image }}" class="rounded" style="width: 50%">
                    </div>
                    <div class="mx-5 py-4"><p>{!! $blog->content !!}</p></div>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection